version: '3'
services:
  #ubuntu: # debug: docker exec -i -t ubuntu bash
  #  image: ubuntu
  #  command: tail -F anything
  #  networks:
  #    - db_nw
  #    - web_nw

  scan7:
    container_name: scan7
    image: scan7
    depends_on:
      - postgres_db
    networks:
      - db_nw
      - web_nw
    ports:
      - "80:5000"
    restart: unless-stopped
    environment:
      - DEV_DATABASE_URL=postgresql://db1:db1@postgres_db/db1
      - DEFAULT_EMAIL=admin@example.com
      - DEFAULT_PASSWORD=admin

  postgres_db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-db1}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-db1}
      PGDATA: /data/postgres
    #volumes:
    #   - postgres:/data/postgres
    #ports:
    #  - "5432:5432"
    networks:
      - db_nw
    restart: unless-stopped

  #redis_server:
  #  container_name: redis_server
  #  image: redis
  #  networks:
  #    - db_nw
  #    - web_nw
  #  restart: unless-stopped

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  dbdata:
