def get_graph(name):
  SIMPLE_LINE = {
   "chart":{
      "type":"area",
      "height":"250px"
   },
   "title":{
      "text":"",
      "style":{
         "fontSize":"18px"
      }
   },
   "dataLabels":{
      "enabled":True
   },
   "series":[
   ],
   "labels":[
   ],
   "fill":{
      "type":"gradient",
      "gradient":{
         "shadeIntensity":1,
         "opacityFrom":0.7,
         "opacityTo":0.9,
         "stops":[
            0,
            90,
            100
         ]
      }
   },
   "xaxis":{
      "categories":[
      ]
   }
  }

  MULTI_BAR = {
   "series":[
   ],
   "colors":[],
   "title":{
      "text":"",
      "style":{
         "fontSize":"18px"
      }
   },
   "chart":{
      "type":"bar",
      "width":"100%",
      "height":"100%"
   },
   "plotOptions":{
      "bar":{
         "horizontal":False,
         "columnWidth":"55%",
         "endingShape":"rounded"
      }
   },
   "dataLabels":{
      "enabled":False
   },
   "stroke":{
      "show":True,
      "width":2,
      "colors":[
         "transparent"
      ]
   },
   "xaxis":{
      "categories":[
      ],
      "labels":{
         "style":{
            "fontSize":"11px",
            #"cssClass":".apexcharts-margin"
         },
         "hideOverlappingLabels":False,
         "show":"1",
         "rotate":0,
         "rotateAlways":False,
#         "minHeight":100,
#         "maxHeight":2000
      }
   },
   "yaxis":{
      "title":{
         "text":""
      }
   },
   "fill":{
      "opacity":1
   },
   "tooltip":{
      "y":{
      }
   }
  }

  DONUT = {
   "chart":{
      "type":"donut",
      "width":"100%",
      #"height":300
   },
   "dataLabels":{
      "enabled":False
   },
   "plotOptions":{
      "pie":{
         "customScale":0.8,
         "donut":{
            "size":"60%"
         },
         "offsetY":20
      },
      "stroke":{
         "colors":["transparent"]
      }
   },
   "colors":[],
   "title":{
      "text":"",
      "style":{
         "fontSize":"18px",
         "fontWeight":"500"
      }
   },
   "series":[
   ],
   "labels":[
   ],
   "legend":{
      "position":"left",
      "offsetY":80,
      "width":"30%"
   }
  }

  MULTI_AREA = {
   "chart":{
      "height":340,
      "type":"area",
      "zoom":{
         "enabled":False
      }
   },
   "stroke":{
      "curve":"straight"
   },
   "colors":"colorPalette",
   "series":[
   ],
   "fill":{
      "opacity":1
   },
   "title":{
      "text":"",
      "align":"left",
      "style":{
         "fontSize":"18px"
      }
   },
   "markers":{
      "size":0,
      "style":"hollow",
      "hover":{
         "opacity":5
      }
   },
   "tooltip":{
      "intersect":True,
      "shared":False
   },
   "xaxis":{
      "tooltip":{
         "enabled":False
      },
      "labels":{
         "show":False
      },
      "axisTicks":{
         "show":False
      }
   },
   "yaxis":{
      "tickAmount":4,
      "max":12,
      "axisBorder":{
         "show":False
      },
      "axisTicks":{
         "show":False
      },
      "labels":{
         "style":{
            "colors":"#78909c"
         }
      }
   },
   "legend":{
      "show":False
   }
  }

  MULTI_LINE = {
   "chart":{
      "height":328,
      "type":"line",
      "zoom":{
         "enabled":False
      },
      "dropShadow":{
         "enabled":True,
         "top":3,
         "left":2,
         "blur":4,
         "opacity":1
      }
   },
   "stroke":{
      "curve":"smooth",
      "width":2
   },
   "colors":[
   ],
   "series":[
   ],
   "title":{
      "text":"",
      "align":"left",
      "offsetY":25,
      "offsetX":20
   },
   "subtitle":{
      "text":"",
      "offsetY":55,
      "offsetX":20
   },
   "markers":{
      "size":6,
      "strokeWidth":0,
      "hover":{
         "size":9
      }
   },
   "grid":{
      "show":True,
      "padding":{
         "bottom":0
      }
   },
   "labels":[
   ],
   "xaxis":{
      "tooltip":{
         "enabled":False
      }
   },
   "legend":{
      "position":"top",
      "horizontalAlign":"right",
      "offsetY":-20
   }
  }

  MULTI_CIRCLE = {
   "chart":{
      "type":"radialBar",
      "height":350,
      "width":380
   },
   "plotOptions":{
      "radialBar":{
         "size":"undefined",
         "inverseOrder":True,
         "hollow":{
            "margin":5,
            "size":"48%",
            "background":"transparent"
         },
         "track":{
            "show":False
         },
         "startAngle":-180,
         "endAngle":180
      }
   },
   "stroke":{
      "lineCap":"round"
   },
   "series":[
   ],
   "labels":[
   ],
   "legend":{
      "show":True,
      "floating":True,
      "position":"right",
      "offsetX":70,
      "offsetY":240
   }
  }

  SPARK_LINE = {
   "chart":{
      "id":"sparkline1",
      "type":"line",
      "height":100,
      "sparkline":{
         "enabled":True
      },
      "group":""
   },
   "series":[
   ],
   "stroke":{
      "curve":"smooth"
   },
   "markers":{
      "size":0
   },
   "tooltip":{
      "fixed":{
         "enabled":True,
         "position":"right"
      },
      "x":{
         "show":False
      }
   },
   "title":{
      "text":"",
      "style":{
         "fontSize":"30px"
      }
   },
   "colors":[
   ]
  }

  SIMPLE_RADIAL = {
   "chart":{
      "type":"radialBar",
      "height":266,
      "zoom":{
         "enabled":False
      },
      "offsetY":20
   },
   "colors":[
      "#E91E63"
   ],
   "plotOptions":{
      "radialBar":{
         "dataLabels":{
            "name":{
               "show":False
            },
            "value":{
               "offsetY":0
            }
         }
      }
   },
   "series":[
   ],
   "theme":{
      "monochrome":{
         "enabled":False
      }
   },
   "legend":{
      "show":False
   },
   "title":{
      "text":"",
      "align":"left"
   }
  }
  map = {
    "simple_line":SIMPLE_LINE,
    "multi_bar":MULTI_BAR,
    "donut":DONUT,
    "multi_area":MULTI_AREA,
    "multi_line":MULTI_LINE,
    "multi_cicle":MULTI_CIRCLE,
    "spark_line":SPARK_LINE,
    "simple_radial":SIMPLE_RADIAL,
  }
  return map.get(name)
