"""empty message

Revision ID: 085343396393
Revises: 9c95f00565e4
Create Date: 2021-02-26 06:14:42.658529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085343396393'
down_revision = '9c95f00565e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_data', sa.Column('host', sa.String(), nullable=True))
    op.add_column('app_data', sa.Column('scan_id', sa.Integer(), nullable=True))
    op.add_column('port_data', sa.Column('host', sa.String(), nullable=True))
    op.add_column('port_data', sa.Column('scan_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('port_data', 'scan_id')
    op.drop_column('port_data', 'host')
    op.drop_column('app_data', 'scan_id')
    op.drop_column('app_data', 'host')
    # ### end Alembic commands ###
