"""empty message

Revision ID: 1e0434c8c45b
Revises: 4c4e0b4f4761
Create Date: 2021-03-24 21:33:18.921765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e0434c8c45b'
down_revision = '4c4e0b4f4761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_secret',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('line_number', sa.String(), nullable=True),
    sa.Column('offender', sa.String(), nullable=True),
    sa.Column('commit', sa.String(), nullable=True),
    sa.Column('rule', sa.String(), nullable=True),
    sa.Column('commit_message', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_vuln',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('identifiers', sa.String(), nullable=True),
    sa.Column('cpe', sa.String(), nullable=True),
    sa.Column('cve', sa.String(), nullable=True),
    sa.Column('cwe', sa.String(), nullable=True),
    sa.Column('vulnerability', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('cvssv2_severity', sa.String(), nullable=True),
    sa.Column('cvssv2_score', sa.Float(), nullable=True),
    sa.Column('cvssv2', sa.String(), nullable=True),
    sa.Column('cvssv3_base_severity', sa.String(), nullable=True),
    sa.Column('cvssv3_base_score', sa.Float(), nullable=True),
    sa.Column('cvssv3', sa.String(), nullable=True),
    sa.Column('cpe_confidence', sa.String(), nullable=True),
    sa.Column('evidence_count', sa.Float(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exclusion')
    op.drop_table('iplocation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iplocation',
    sa.Column('ip_from', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ip_to', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ip_from', 'ip_to', name='iplocation_pkey')
    )
    op.create_table('exclusion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_added', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='exclusion_pkey'),
    sa.UniqueConstraint('value', name='exclusion_value_key')
    )
    op.drop_table('file_vuln')
    op.drop_table('file_secret')
    # ### end Alembic commands ###
