"""empty message

Revision ID: 329c7da05e93
Revises: 9fc798385835
Create Date: 2021-02-26 13:26:16.290393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329c7da05e93'
down_revision = '9fc798385835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_address', sa.Column('is_global', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_address', 'is_global')
    # ### end Alembic commands ###
