"""empty message

Revision ID: 5e12f37d3dbe
Revises: 7653ab920f87
Create Date: 2021-04-02 02:06:41.698823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e12f37d3dbe'
down_revision = '7653ab920f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_dependency', sa.Column('repo_id', sa.Integer(), nullable=True))
    op.add_column('package_dependency', sa.Column('repo_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package_dependency', 'repo_name')
    op.drop_column('package_dependency', 'repo_id')
    # ### end Alembic commands ###
