"""empty message

Revision ID: 968978d3fe29
Revises: a12bbfb5ceaf
Create Date: 2021-02-24 15:50:36.847398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968978d3fe29'
down_revision = 'a12bbfb5ceaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_data', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.drop_constraint('app_data_asset_fkey', 'app_data', type_='foreignkey')
    op.create_foreign_key(None, 'app_data', 'asset', ['asset_id'], ['id'])
    op.drop_column('app_data', 'asset')
    op.add_column('asset_certificate', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.drop_constraint('asset_certificate_asset_fkey', 'asset_certificate', type_='foreignkey')
    op.create_foreign_key(None, 'asset_certificate', 'asset', ['asset_id'], ['id'])
    op.drop_column('asset_certificate', 'asset')
    op.add_column('asset_whois', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.drop_constraint('asset_whois_asset_fkey', 'asset_whois', type_='foreignkey')
    op.create_foreign_key(None, 'asset_whois', 'asset', ['asset_id'], ['id'])
    op.drop_column('asset_whois', 'asset')
    op.add_column('port_data', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.drop_constraint('port_data_asset_fkey', 'port_data', type_='foreignkey')
    op.create_foreign_key(None, 'port_data', 'asset', ['asset_id'], ['id'])
    op.drop_column('port_data', 'asset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('port_data', sa.Column('asset', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'port_data', type_='foreignkey')
    op.create_foreign_key('port_data_asset_fkey', 'port_data', 'asset', ['asset'], ['id'])
    op.drop_column('port_data', 'asset_id')
    op.add_column('asset_whois', sa.Column('asset', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'asset_whois', type_='foreignkey')
    op.create_foreign_key('asset_whois_asset_fkey', 'asset_whois', 'asset', ['asset'], ['id'])
    op.drop_column('asset_whois', 'asset_id')
    op.add_column('asset_certificate', sa.Column('asset', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'asset_certificate', type_='foreignkey')
    op.create_foreign_key('asset_certificate_asset_fkey', 'asset_certificate', 'asset', ['asset'], ['id'])
    op.drop_column('asset_certificate', 'asset_id')
    op.add_column('app_data', sa.Column('asset', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'app_data', type_='foreignkey')
    op.create_foreign_key('app_data_asset_fkey', 'app_data', 'asset', ['asset'], ['id'])
    op.drop_column('app_data', 'asset_id')
    # ### end Alembic commands ###
