"""empty message

Revision ID: 997c957e1fa6
Revises: 
Create Date: 2021-02-21 17:22:54.357494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997c957e1fa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_scan', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_scan', 'status')
    # ### end Alembic commands ###
