"""empty message

Revision ID: 9c95f00565e4
Revises: 968978d3fe29
Create Date: 2021-02-26 02:43:45.651594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c95f00565e4'
down_revision = '968978d3fe29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('wildcard', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'wildcard')
    # ### end Alembic commands ###
