"""empty message

Revision ID: 9fc798385835
Revises: 085343396393
Create Date: 2021-02-26 06:33:31.924374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc798385835'
down_revision = '085343396393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'online')
    # ### end Alembic commands ###
