"""empty message

Revision ID: bd255b7a24f5
Revises: 997c957e1fa6
Create Date: 2021-02-21 20:33:43.382301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd255b7a24f5'
down_revision = '997c957e1fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository', 'enabled')
    # ### end Alembic commands ###
