"""empty message

Revision ID: f7bf5ced64ea
Revises: bd255b7a24f5
Create Date: 2021-02-22 05:03:25.748394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7bf5ced64ea'
down_revision = 'bd255b7a24f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('part', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pattern')
    # ### end Alembic commands ###
